// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mVvTprmJIU53hsk3NJNWAdZz3YPo_RI',
    appId: '1:8945929363:web:1aa7f4d48466b3c0949166',
    messagingSenderId: '8945929363',
    projectId: 'calculadora-gorjeta-d1d12',
    authDomain: 'calculadora-gorjeta-d1d12.firebaseapp.com',
    storageBucket: 'calculadora-gorjeta-d1d12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQ6CJy0zdFC-AN3KKiocRmoMXMQuxLKo',
    appId: '1:8945929363:android:69043cfb3bdf2c2f949166',
    messagingSenderId: '8945929363',
    projectId: 'calculadora-gorjeta-d1d12',
    storageBucket: 'calculadora-gorjeta-d1d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUV9vnPegBBh3CQpKuylDBPt2HDgEHAbs',
    appId: '1:8945929363:ios:f7bca5172b035122949166',
    messagingSenderId: '8945929363',
    projectId: 'calculadora-gorjeta-d1d12',
    storageBucket: 'calculadora-gorjeta-d1d12.firebasestorage.app',
    iosBundleId: 'com.example.calculadoraGorjeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUV9vnPegBBh3CQpKuylDBPt2HDgEHAbs',
    appId: '1:8945929363:ios:f7bca5172b035122949166',
    messagingSenderId: '8945929363',
    projectId: 'calculadora-gorjeta-d1d12',
    storageBucket: 'calculadora-gorjeta-d1d12.firebasestorage.app',
    iosBundleId: 'com.example.calculadoraGorjeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1mVvTprmJIU53hsk3NJNWAdZz3YPo_RI',
    appId: '1:8945929363:web:efddcaecfb2b2679949166',
    messagingSenderId: '8945929363',
    projectId: 'calculadora-gorjeta-d1d12',
    authDomain: 'calculadora-gorjeta-d1d12.firebaseapp.com',
    storageBucket: 'calculadora-gorjeta-d1d12.firebasestorage.app',
  );
}
